# Generated by Django 4.2.4 on 2023-12-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('is_master', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
